# Домашнее задание HW01

## 1) Работа с NumPy

In [1]:
# 1. Импорт библиотеки NumPy с общепринятым сокращением
import numpy as np

## 2) Создание массивов

In [3]:
# 1) Создание массива из обычного списка
array_from_list = np.array([1, 2, 3, 4, 5])
print("Массив из списка:", array_from_list)

Массив из списка: [1 2 3 4 5]


In [4]:
# Создание двумерного массива из списка списков
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Двумерный массив:", array_2d)

Двумерный массив: [[1 2 3]
 [4 5 6]]


In [6]:
# 2) Создание массивов с помощью функций NumPy
zeros_array = np.zeros(5)  # Массив из нулей
ones_array = np.ones((2, 3)) # Двумерный массив из единиц
arange_array = np.arange(0, 10, 2) # Массив с шагом 2 от 0 до 10

print("Массив из нулей:", zeros_array)
print("Массив из единиц:", ones_array)
print("Массив arange:", arange_array)

Массив из нулей: [0. 0. 0. 0. 0.]
Массив из единиц: [[1. 1. 1.]
 [1. 1. 1.]]
Массив arange: [0 2 4 6 8]


## 3) Атрибуты массивов

In [5]:
print("Форма массива array_2d:", array_2d.shape)
print("Тип данных массива array_2d:", array_2d.dtype)
print("Размерность массива array_2d:", array_2d.ndim)
print("Количество элементов array_2d:", array_2d.size)

Форма массива array_2d: (2, 3)
Тип данных массива array_2d: int32
Размерность массива array_2d: 2
Количество элементов array_2d: 6


## 4) Индексирование и срезы

In [13]:
array = np.array([10, 20, 30, 40, 50, 60])

# Получение отдельного элемента
print("Элемент с индексом 2:", array[2])

# Извлечение подмассива с помощью среза
print("Срез [1:4]:", array[1:4]) # с 1 по 4 элемент
print("Срез [::2]:", array[::2])  # Каждый второй элемент

# Индексирование в двумерном массиве
print("Двумерный массив:\n", array_2d)
print("Элемент [1,2]:", array_2d[1, 2])  # Строка 1, столбец 2
print("Срез первой строки:", array_2d[0, :])  # Вся первая строка

Элемент с индексом 2: 30
Срез [1:4]: [20 30 40]
Срез [::2]: [10 30 50]
Двумерный массив:
[[1 2 3]
 [4 5 6]]
Элемент [1,2]: 6
Срез первой строки: [1 2 3]


## 5) Векторные операции и статистика

In [10]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Поэлементное сложение
sum_result = a + b
print("Поэлементное сложение:", sum_result)

# Поэлементное умножение
mult_result = a * b
print("Поэлементное умножение:", mult_result)

# Базовые статистики
data = np.array([2, 4, 6, 8, 10])
print("Статистики для массива:", data)
print("Среднее значение:", np.mean(data))
print("Сумма элементов:", np.sum(data))
print("Минимальное значение:", np.min(data))
print("Максимальное значение:", np.max(data))
print("Стандартное отклонение:", np.std(data))

Поэлементное сложение: [ 6  8 10 12]
Поэлементное умножение: [ 5 12 21 32]
Статистики для массива: [ 2  4  6  8 10]
Среднее значение: 6.0
Сумма элементов: 30
Минимальное значение: 2
Максимальное значение: 10
Стандартное отклонение: 2.8284271247461903


## 6) Дополнительные примеры

In [9]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Матрица 3x3:\n", matrix)

# Сумма по столбцам
print("Сумма по столбцам:", np.sum(matrix, axis=0))

# Сумма по строкам
print("Сумма по строкам:", np.sum(matrix, axis=1))

# Транспонирование матрицы
print("Транспонированная матрица:\n", matrix.T)

Матрица 3x3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Сумма по столбцам: [12 15 18]
Сумма по строкам: [ 6 15 24]
Транспонированная матрица:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
